# Generated by Django 4.1 on 2022-09-01 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Materiel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeTraitement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to='')),
            ],
        ),
        migrations.AlterField(
            model_name='objet',
            name='DateDebutEmprunt',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 9, 1, 12, 45, 47, 24462)),
        ),
        migrations.AlterField(
            model_name='objet',
            name='DateFinEmprunt',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 9, 1, 12, 45, 47, 24462)),
        ),
    ]
