# Generated by Django 4.1 on 2022-09-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partenaires',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('NomPartenaire', models.TextField(null=True)),
                ('Description', models.TextField(null=True)),
                ('Image', models.FileField(upload_to='')),
                ('SiteWeb', models.TextField(null=True)),
            ],
        ),
    ]
