# Generated by Django 4.1 on 2022-11-04 09:14

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0003_evenementsbdd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LogoFooterAssociation', models.TextField(null=True)),
                ('LogoFooterEcoles', models.ImageField(blank=True, null=True, upload_to='img')),
                ('MentionsLegales', tinymce.models.HTMLField()),
                ('PolitiqueDeConfidentialite', tinymce.models.HTMLField()),
                ('AdresseMail', models.CharField(max_length=100)),
                ('NumeroTelephone', models.CharField(max_length=500)),
                ('Adresse', models.CharField(max_length=100)),
                ('Ville', models.CharField(max_length=100)),
                ('PhotoCouverture', models.ImageField(blank=True, null=True, upload_to='img')),
                ('NomAssociationBasPage', models.CharField(max_length=120)),
            ],
        ),
    ]
