# Generated by Django 4.1 on 2022-11-04 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0004_parametres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametres',
            name='LogoFooterAssociation',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
