# Generated by Django 4.1 on 2022-11-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0005_alter_parametres_logofooterassociation'),
    ]

    operations = [
        migrations.AddField(
            model_name='parametres',
            name='lienDrive',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='parametres',
            name='lienGit',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='partenairesbdd',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='img'),
        ),
    ]
