# Generated by Django 4.1 on 2022-11-03 21:19

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Formation', '0002_remove_formation_lienformationecrite_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='TextFormation',
            field=tinymce.models.HTMLField(default=2008),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certification',
            name='DateCertificat',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 11, 3, 22, 19, 12, 151316)),
        ),
    ]
