# Generated by Django 4.1 on 2022-11-03 22:12

import datetime
from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Formation', '0004_remove_formation_lienquestionnaire_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='PDFFormationEcrite',
        ),
        migrations.AddField(
            model_name='formation',
            name='Questionnaire',
            field=tinymce.models.HTMLField(default=2008),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certification',
            name='DateCertificat',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 11, 3, 23, 12, 3, 150240)),
        ),
    ]
