# Generated by Django 4.1 on 2022-09-11 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Partenaires',
            new_name='Partenairesbdd',
        ),
    ]
