# Generated by Django 4.1 on 2022-09-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0002_rename_partenaires_partenairesbdd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenementsbdd',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('TitreEvenement', models.TextField(null=True)),
                ('Description', models.TextField(null=True)),
                ('Image', models.FileField(upload_to='')),
            ],
        ),
    ]
