# Generated by Django 4.1 on 2022-09-11 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeTraitement',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('image', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Emprunt',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idObjetEmprunt', models.CharField(max_length=100)),
                ('NomEmprunteur', models.CharField(max_length=100)),
                ('Caution', models.CharField(max_length=100)),
                ('DateDebutEmprunt', models.DateField(blank=True, default=datetime.datetime(2022, 9, 11, 15, 18, 46, 749651))),
                ('DateFinEmprunt', models.DateField(blank=True, default=datetime.datetime(2022, 9, 11, 15, 18, 46, 749651))),
            ],
        ),
        migrations.CreateModel(
            name='Objet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('CodeBarre', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('appartenance', models.TextField(null=True)),
            ],
        ),
    ]
