# Generated by Django 4.1 on 2022-09-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('NomCertificat', models.TextField(null=True)),
                ('Description', models.TextField(null=True)),
                ('Duree', models.TextField(null=True)),
                ('LienQuestionnaire', models.TextField(null=True)),
                ('LienFormationEcrite', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PersoneAvecCertificat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('NomPersonne', models.TextField(null=True)),
                ('PrenomPersonne', models.TextField(null=True)),
                ('mailPersonne', models.TextField(null=True)),
                ('NomFormationCertificat', models.TextField(null=True)),
                ('DateCertificat', models.TextField(null=True)),
            ],
        ),
    ]
