# Generated by Django 4.1 on 2022-10-04 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MembreINTech',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Nom', models.TextField(null=True)),
                ('Prenom', models.TextField(null=True)),
                ('Ecole', models.TextField(null=True)),
                ('mail', models.EmailField(max_length=254)),
                ('mdp', models.TextField(null=True)),
                ('role', models.CharField(choices=[('Membre', 'Membre'), ('Bureau', 'Bureau')], max_length=100, null=True)),
                ('ValidationCompte', models.BooleanField(default=False)),
            ],
        ),
    ]
