# Generated by Django 4.1 on 2022-10-04 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='infoMembreINTech',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idCompte', models.IntegerField()),
                ('Ecole', models.TextField(null=True)),
                ('role', models.CharField(choices=[('Membre', 'Membre'), ('Bureau', 'Bureau')], max_length=100, null=True)),
                ('ValidationCompte', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='MembreINTech',
        ),
    ]
